---
- include_vars: passwords.yml

# Vorbereitung f√ºr die Virtualisierung mit libvirt/KVM
- name: install bridge-utils
  apt:
    pkg: "bridge-utils"
    update_cache: yes
    state: installed

- name: IPv4 Paketweiterleitung aktivieren
  sysctl: name="net.ipv4.conf.all.forwarding" value=1 sysctl_set=yes state=present reload=yes

- name: Enable Proxy Arp
  sysctl: name="net.ipv4.conf.all.proxy_arp" value=1 sysctl_set=yes state=present reload=yes
  when: 'hoster is defined and hoster == "online.net"'

- name: ICMPv4 Weiterleitung der VMs zum Gateway unterbinden
  sysctl: name="net.ipv4.conf.eth0.send_redirects" value=0 sysctl_set=yes state=present reload=yes

- name: IPv6 Paketweiterleitung aktivieren
  sysctl: name="net.ipv6.conf.all.forwarding" value=1 sysctl_set=yes state=present reload=yes

#TODO: Don't restart network when VMs are running
- name: configure /etc/network/interfaces/
  template: src="interfaces.j2" dest="/etc/network/interfaces"
  notify:
    - restart networking

- name: Configure dhcpv6 client conf file
  template:
    src: "dhclient6.conf.j2"
    dest: "/etc/dhcp/dhclient6.conf"
  when: 'network.own_v6.type == "dhcp"'

- name: Configure systemd service for dhclient
  template:
    src: "dhclient.service.j2"
    dest: "/etc/systemd/system/dhclient.service"
  when: 'network.own_v6.type == "dhcp"'

- name: Enable and start the dhclient systemd service
  systemd:
    name: dhclient.service
    enabled: yes
    state: started

- name: Execute all triggered handlers
  meta: flush_handlers

